#JOB & STAGE name should not have any spaces
#default azure runs stages parallely, to make it sequential we should write condition

trigger:
- main

pool: d65

variables:
  COMPONENT: shipping

resources:
  repositories:
  - repository: templates
    type: github
    name: devopsravi9/roboshop-azure-devops-templates
    endpoint: devopsravi9

stages:
- template: maven.yml@templates



